// Tarjima uchun tillar: kod → AI'ga beriladigan inglizcha nom.
// Ilovadagi ro'yxat (lib/models/translate_language.dart) shu kodlar bilan mos.
const LANGUAGES = {
  uz: 'Uzbek (Latin script)',
  'uz-Cyrl': 'Uzbek (Cyrillic script)',
  ru: 'Russian',
  en: 'English',
  kaa: 'Karakalpak',
  kk: 'Kazakh',
  ky: 'Kyrgyz',
  tg: 'Tajik',
  tk: 'Turkmen',
  tr: 'Turkish',
  az: 'Azerbaijani',
  ko: 'Korean',
  ja: 'Japanese',
  zh: 'Chinese (Simplified)',
  ar: 'Arabic',
  fa: 'Persian',
  de: 'German',
  fr: 'French',
  es: 'Spanish',
  it: 'Italian',
  pt: 'Portuguese',
  pl: 'Polish',
  uk: 'Ukrainian',
  be: 'Belarusian',
  hi: 'Hindi',
  ur: 'Urdu',
  id: 'Indonesian',
  ms: 'Malay',
  vi: 'Vietnamese',
  th: 'Thai',
  he: 'Hebrew',
  el: 'Greek',
  nl: 'Dutch',
  sv: 'Swedish',
  cs: 'Czech',
  ro: 'Romanian',
  hu: 'Hungarian',
  bg: 'Bulgarian',
  ka: 'Georgian',
  hy: 'Armenian',
  mn: 'Mongolian',
};

module.exports = { LANGUAGES };
